name: Assembly and release

on:
  workflow_call:
    secrets:
      JRELEASER_NEXUS2_USERNAME:
        required: true
      JRELEASER_NEXUS2_PASSWORD:
        required: true
      JRELEASER_GPG_PASSPHRASE:
        required: true
      JRELEASER_GPG_SECRET_KEY:
        required: true
      JRELEASER_GPG_PUBLIC_KEY:
        required: true
      GITHUB_TOKEN:
        required: true

  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: ./.github/workflows/test.yaml
    - name: Publish
      env:
        JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
        JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
      with:
        arguments: ./gradlew jar sourcesJar javadocJar jreleaserFullRelease --no-daemon --stacktrace
