name: Tests

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: ls -lh
    - name: Run docker-compose
      run: docker-compose up -d
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      with:
        arguments: ./gradlew test
